### ISSUE TITLE
Npm respository is not working

### ISSUE THREAD

**Issue by Ardakilic** [timschlechter/bootstrap-tagsinput#366]
Hello,

I cannot install bootstrap-tagsinput over npm.

I have this as `devDependencies` in my `package.json`, this used to work until recently:

```
"bootstrap-tagsinput": "^0.4.2",
```

It's reporting this on terminal:

```shell
npm http GET https://registry.npmjs.org/bootstrap-tagsinput
npm http 404 https://registry.npmjs.org/bootstrap-tagsinput
npm ERR! TypeError: Cannot read property 'latest' of undefined
npm ERR!     at next (/usr/local/lib/node_modules/npm/lib/cache.js:744:35)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/cache.js:732:5
npm ERR!     at saved (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:148:7)
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>
 
npm ERR! System Linux 3.13.0-53-generic
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! cwd /home/arda/Web/arda
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! type non_object_property_load
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/arda/Web/arda/npm-debug.log
npm ERR! not ok code 0
```

Any known mainetnance happening?

Thanks in advance,

**Comment by lucknerjb** [comment]
The package has been republished. Only the current (0.5.0) release is available: https://www.npmjs.com/package/bootstrap-tagsinput

**Comment by Ardakilic** [comment]
Sorry for the late reply,

I can confirm this can be marked as solved,

Thanks again!
